# tasks file for vm-create
- name: Clone VM from template with dhcp
vmware_guest:
validate_certs: “{{ validate_certs | default(‘False’) }}”
hostname: “{{ vcenter_hostname }}”
username: “{{ vcenter_username }}”
password: “{{ vcenter_password }}”
datacenter: “{{ vm_datacenter }}”
name: “{{ vm_name }}”
folder: “{{ vm_folder }}”
template: “{{ vm_template }}”
state: poweredon
annotation: “{{ vm_notes | default(‘Provisioned by ansible’) }}”
cluster: “{{ vm_cluster }}”
hardware:
num_cpus: “{{ cpu }}”
memory_mb: “{{ mem_mb }}”
hotadd_cpu: “{{ hot_add_cpu | default(‘True’) }}”
hotremove_cpu: “{{ hot_remove_cpu | default(‘True’) }}”
hotadd_memory: “{{ hot_add_memory | default(‘True’) }}”
disk:
— size_gb: “{{ disk_size | default(‘16’) }}”
type: “{{ vm_disk_type | default(‘thin’) }}”
datastore: “{{ vm_datastore }}”
networks:
— name: “{{ vm_port_group | default(‘VM Network’) }}”
wait_for_ip_address: yes
register: dynamic_vm
when: network_type == ‘dhcp’
- name: Clone VM from template with static IP
vmware_guest:
validate_certs: “{{ validate_certs | default(‘False’) }}”
hostname: “{{ vcenter_hostname }}”
username: “{{ vcenter_username }}”
password: “{{ vcenter_password }}”
datacenter: “{{ vm_datacenter }}”
name: “{{ vm_name }}”
folder: “{{ vm_folder }}”
template: “{{ vm_template }}”
state: poweredon
annotation: “{{ vm_notes | default(‘Provisioned by ansible’) }}”
cluster: “{{ vm_cluster }}”
hardware:
num_cpus: “{{ cpu }}”
memory_mb: “{{ mem_mb }}”
hotadd_cpu: “{{ hot_add_cpu | default(‘True’) }}”
hotremove_cpu: “{{ hot_remove_cpu | default(‘True’) }}”
hotadd_memory: “{{ hot_add_memory | default(‘True’) }}”
disk:
— size_gb: “{{ disk_size | default(‘16’) }}”
type: “{{ vm_disk_type | default(‘thin’) }}”
datastore: “{{ vm_datastore }}”
networks:
— name: “{{ vm_port_group }}”
type: static
ip: “{{ vm_ip }}”
netmask: “{{ netmask }}”
dns_servers:
— “{{ dns_server1 }}”
— “{{ dns_server2 }}”
gateway: “{{ network_gateway }}”
wait_for_ip_address: yes
register: static_vm
when: network_type == ‘static’